# Generated by Django 2.1.7 on 2020-07-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200721_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('emali', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
