# Generated by Django 3.0.4 on 2020-07-12 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 7, 12, 17, 0, 35, 52993, tzinfo=utc))),
                ('categary', models.CharField(max_length=6000)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
