# Generated by Django 3.0.4 on 2020-07-13 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 6, 15, 17, 472800, tzinfo=utc)),
        ),
    ]
