# Generated by Django 3.0.4 on 2020-07-15 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200714_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 12, 6, 36, 476035, tzinfo=utc)),
        ),
    ]
