# Generated by Django 3.0.4 on 2020-07-15 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200715_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 14, 42, 51, 392256, tzinfo=utc)),
        ),
    ]
