# Generated by Django 3.0.4 on 2020-07-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200716_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='null', upload_to='blog/images'),
        ),
    ]
