# Generated by Django 2.1.7 on 2020-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200722_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcommet',
            fields=[
                ('son', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
